@startuml
	left to right direction
	skinparam packageStyle rectangle
	Operador <<persona>> as Actor
	rectangle {
		(Agregar Reperfilamiento de Personas Físicas) as CreateUC <<usuario>>
		(Editar Reperfilamiento de Personas Físicas) as EditUC <<usuario>>
		(Eliminar Reperfilamiento de Personas Físicas) as DeleteUC <<usuario>>
		Actor -> CreateUC
		Actor -> EditUC
		Actor -> SearchUC
		Actor --> DeleteUC
		EditUC .> SearchUC : include
		DeleteUC .> SearchUC : include
	}
@enduml
