package com.aforebanamex.plata.cg.dominio.repository.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import com.aforebanamex.plata.base.helper.NegativaPerfilamientoConstantesHelper;
import com.aforebanamex.plata.comunes.model.NegativaPerfilamiento;

import com.aforebanamex.plata.comunes.model.Contrato;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.NoSi;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.ConocimientoExperiencia;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.ConocimientoExperiencia;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.Dummy;
import com.aforebanamex.plata.comunes.model.NoSi;
import com.aforebanamex.plata.comunes.model.SituacionFinancieraActual;
import com.aforebanamex.plata.comunes.model.SituacionFinancieraActual;
import com.aforebanamex.plata.comunes.model.SituacionFinancieraActual;

public class NegativaPerfilamientoMapper implements org.springframework.jdbc.core.RowMapper<NegativaPerfilamiento> {

	@Override
	public NegativaPerfilamiento mapRow(ResultSet rs, int arg1) throws SQLException {

		NegativaPerfilamiento negativaPerfilamiento = new NegativaPerfilamiento();
		
		//negativaPerfilamiento.setIdSubproceso(rs.getLong(InformeConstantesHelper.CVE_SUBPROCESO_ID));
		negativaPerfilamiento.setIdNegativaPerfilamiento(rs.getLong(NegativaPerfilamientoConstantesHelper.ID_NEGATIVAPERFILAMIENTO));
    		Contrato contrato = new Contrato();
    		contrato.setIdContrato(rs.getLong(NegativaPerfilamientoConstantesHelper.ID_CONTRATO));
    		contrato.setNoContrato(rs.getString(NegativaPerfilamientoConstantesHelper.CONTRATO));
    		negativaPerfilamiento.setContrato(contrato);
    				
    		negativaPerfilamiento.setNombre(rs.getString(NegativaPerfilamientoConstantesHelper.NOMBRE));
    		negativaPerfilamiento.setPerfilActual(rs.getString(NegativaPerfilamientoConstantesHelper.PERFILACTUAL));
    		Dummy personaPerfilar = new Dummy();
    		personaPerfilar.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		personaPerfilar.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(personaPerfilar);
    		negativaPerfilamiento.setPorcentajeLiquidez(rs.getString(NegativaPerfilamientoConstantesHelper.PORCENTAJELIQUIDEZ));
    		negativaPerfilamiento.setMontoLiquidez(rs.getDate(NegativaPerfilamientoConstantesHelper.MONTOLIQUIDEZ));
    		negativaPerfilamiento.setPorcentajeCortoPlazo(rs.getString(NegativaPerfilamientoConstantesHelper.PORCENTAJECORTOPLAZO));
    		negativaPerfilamiento.setMontoCortoPlazo(rs.getDouble(NegativaPerfilamientoConstantesHelper.MONTOCORTOPLAZO));
    		negativaPerfilamiento.setPorcentajeLargoPlazo(rs.getString(NegativaPerfilamientoConstantesHelper.PORCENTAJELARGOPLAZO));
    		negativaPerfilamiento.setMontoLargoPlazo(rs.getDouble(NegativaPerfilamientoConstantesHelper.MONTOLARGOPLAZO));
    		negativaPerfilamiento.setPorcentajePatrimonioLiquidoTotal(rs.getString(NegativaPerfilamientoConstantesHelper.PORCENTAJEPATRIMONIOLIQUIDOTOTAL));
    		negativaPerfilamiento.setMontoPatrimonioLiquidoTotal(rs.getDouble(NegativaPerfilamientoConstantesHelper.MONTOPATRIMONIOLIQUIDOTOTAL));
    		Dummy intervaloEdad = new Dummy();
    		intervaloEdad.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		intervaloEdad.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(intervaloEdad);
    		Dummy nivelEstudios = new Dummy();
    		nivelEstudios.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		nivelEstudios.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(nivelEstudios);
    		Dummy ocupacion = new Dummy();
    		ocupacion.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		ocupacion.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(ocupacion);
    		Dummy actividadProfesionalAnterior = new Dummy();
    		actividadProfesionalAnterior.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		actividadProfesionalAnterior.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(actividadProfesionalAnterior);
    		Dummy actividadProfesionalActual = new Dummy();
    		actividadProfesionalActual.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		actividadProfesionalActual.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(actividadProfesionalActual);
    		NoSi actividadRelacionadaInversiones = new NoSi();
    		actividadRelacionadaInversiones.setCveNoSi(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_NO_SI));
    		actividadRelacionadaInversiones.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.NO_SI));
    		negativaPerfilamiento.setNoSi(actividadRelacionadaInversiones);
    		Dummy estrategiaCliente = new Dummy();
    		estrategiaCliente.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		estrategiaCliente.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(estrategiaCliente);
    		Dummy clienteAsesoria = new Dummy();
    		clienteAsesoria.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		clienteAsesoria.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(clienteAsesoria);
    		ConocimientoExperiencia experienciaDeudaGub = new ConocimientoExperiencia();
    		experienciaDeudaGub.setCveConocimientoExperiencia(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_CONOCIMIENTO_EXPERIENCIA));
    		experienciaDeudaGub.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.CONOCIMIENTO_EXPERIENCIA));
    		negativaPerfilamiento.setConocimientoExperiencia(experienciaDeudaGub);
    		Dummy frecuenciaDeudaGub = new Dummy();
    		frecuenciaDeudaGub.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaDeudaGub.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaDeudaGub);
    		Dummy plazoDeudaGub = new Dummy();
    		plazoDeudaGub.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoDeudaGub.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoDeudaGub);
    		Dummy volumenDeudaGub = new Dummy();
    		volumenDeudaGub.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenDeudaGub.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenDeudaGub);
    		ConocimientoExperiencia expDeudaCorp = new ConocimientoExperiencia();
    		expDeudaCorp.setCveConocimientoExperiencia(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_CONOCIMIENTO_EXPERIENCIA));
    		expDeudaCorp.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.CONOCIMIENTO_EXPERIENCIA));
    		negativaPerfilamiento.setConocimientoExperiencia(expDeudaCorp);
    		Dummy frecuenciaDeudaCorp = new Dummy();
    		frecuenciaDeudaCorp.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaDeudaCorp.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaDeudaCorp);
    		Dummy plazoDeudaCorp = new Dummy();
    		plazoDeudaCorp.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoDeudaCorp.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoDeudaCorp);
    		Dummy volumenDeudaCorp = new Dummy();
    		volumenDeudaCorp.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenDeudaCorp.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenDeudaCorp);
    		Dummy expSociedadesInv = new Dummy();
    		expSociedadesInv.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expSociedadesInv.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expSociedadesInv);
    		Dummy frecuenciaSociedadesInv = new Dummy();
    		frecuenciaSociedadesInv.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaSociedadesInv.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaSociedadesInv);
    		Dummy plazoSociedadesInv = new Dummy();
    		plazoSociedadesInv.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoSociedadesInv.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoSociedadesInv);
    		Dummy volumenSociedadesInv = new Dummy();
    		volumenSociedadesInv.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenSociedadesInv.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenSociedadesInv);
    		Dummy expValoresEst = new Dummy();
    		expValoresEst.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expValoresEst.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expValoresEst);
    		Dummy frecuenciaValoresEst = new Dummy();
    		frecuenciaValoresEst.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaValoresEst.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaValoresEst);
    		Dummy plazoValoresEst = new Dummy();
    		plazoValoresEst.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoValoresEst.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoValoresEst);
    		Dummy volumenValoresEst = new Dummy();
    		volumenValoresEst.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenValoresEst.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenValoresEst);
    		Dummy expCertificadosBur = new Dummy();
    		expCertificadosBur.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expCertificadosBur.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expCertificadosBur);
    		Dummy frecuenciaCertificadosBur = new Dummy();
    		frecuenciaCertificadosBur.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaCertificadosBur.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaCertificadosBur);
    		Dummy plazoCertificadosBur = new Dummy();
    		plazoCertificadosBur.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoCertificadosBur.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoCertificadosBur);
    		Dummy volumenCertificadosBur = new Dummy();
    		volumenCertificadosBur.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenCertificadosBur.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenCertificadosBur);
    		Dummy expTitulosOpc = new Dummy();
    		expTitulosOpc.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expTitulosOpc.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expTitulosOpc);
    		Dummy frecuenciaTitulosOpc = new Dummy();
    		frecuenciaTitulosOpc.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaTitulosOpc.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaTitulosOpc);
    		Dummy plazoTitulosOpc = new Dummy();
    		plazoTitulosOpc.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoTitulosOpc.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoTitulosOpc);
    		Dummy volumenTitulosOpc = new Dummy();
    		volumenTitulosOpc.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenTitulosOpc.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenTitulosOpc);
    		Dummy expAcciones = new Dummy();
    		expAcciones.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expAcciones.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expAcciones);
    		Dummy frecuenciaAcciones = new Dummy();
    		frecuenciaAcciones.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaAcciones.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaAcciones);
    		Dummy plazoAcciones = new Dummy();
    		plazoAcciones.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoAcciones.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoAcciones);
    		Dummy volumenAcciones = new Dummy();
    		volumenAcciones.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenAcciones.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenAcciones);
    		Dummy expValoresExt = new Dummy();
    		expValoresExt.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expValoresExt.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expValoresExt);
    		Dummy frecuenciaValoresExt = new Dummy();
    		frecuenciaValoresExt.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaValoresExt.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaValoresExt);
    		Dummy plazoValoresExt = new Dummy();
    		plazoValoresExt.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoValoresExt.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoValoresExt);
    		Dummy volumenValoresExt = new Dummy();
    		volumenValoresExt.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenValoresExt.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenValoresExt);
    		Dummy expTrackers = new Dummy();
    		expTrackers.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expTrackers.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expTrackers);
    		Dummy frecuenciaTrackers = new Dummy();
    		frecuenciaTrackers.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaTrackers.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaTrackers);
    		Dummy plazoTrackers = new Dummy();
    		plazoTrackers.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoTrackers.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoTrackers);
    		Dummy volumenTrackers = new Dummy();
    		volumenTrackers.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenTrackers.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenTrackers);
    		Dummy expCertificadosCap = new Dummy();
    		expCertificadosCap.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		expCertificadosCap.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(expCertificadosCap);
    		Dummy frecuenciaCertificadosCap = new Dummy();
    		frecuenciaCertificadosCap.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		frecuenciaCertificadosCap.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(frecuenciaCertificadosCap);
    		Dummy plazoCertificadosCap = new Dummy();
    		plazoCertificadosCap.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		plazoCertificadosCap.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(plazoCertificadosCap);
    		Dummy volumenCertificadosCap = new Dummy();
    		volumenCertificadosCap.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		volumenCertificadosCap.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(volumenCertificadosCap);
    		Dummy propositoInversion = new Dummy();
    		propositoInversion.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		propositoInversion.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(propositoInversion);
    		Dummy toleranciaRiesgo = new Dummy();
    		toleranciaRiesgo.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		toleranciaRiesgo.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(toleranciaRiesgo);
    		Dummy horizonteInversion = new Dummy();
    		horizonteInversion.setCveDummy(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_DUMMY));
    		horizonteInversion.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.DUMMY));
    		negativaPerfilamiento.setDummy(horizonteInversion);
    		NoSi tieneLimitante = new NoSi();
    		tieneLimitante.setCveNoSi(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_NO_SI));
    		tieneLimitante.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.NO_SI));
    		negativaPerfilamiento.setNoSi(tieneLimitante);
    		SituacionFinancieraActual porcentajeTotalPatrimonio = new SituacionFinancieraActual();
    		porcentajeTotalPatrimonio.setCveSituacionFinancieraActual(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_SITUACION_FINANCIERA_ACTUAL));
    		porcentajeTotalPatrimonio.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.SITUACION_FINANCIERA_ACTUAL));
    		negativaPerfilamiento.setSituacionFinancieraActual(porcentajeTotalPatrimonio);
    		SituacionFinancieraActual porcentajeIngresoAnual = new SituacionFinancieraActual();
    		porcentajeIngresoAnual.setCveSituacionFinancieraActual(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_SITUACION_FINANCIERA_ACTUAL));
    		porcentajeIngresoAnual.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.SITUACION_FINANCIERA_ACTUAL));
    		negativaPerfilamiento.setSituacionFinancieraActual(porcentajeIngresoAnual);
    		SituacionFinancieraActual porcentajeInversiones = new SituacionFinancieraActual();
    		porcentajeInversiones.setCveSituacionFinancieraActual(rs.getLong(NegativaPerfilamientoConstantesHelper.CVE_SITUACION_FINANCIERA_ACTUAL));
    		porcentajeInversiones.setDescripcion(rs.getString(NegativaPerfilamientoConstantesHelper.SITUACION_FINANCIERA_ACTUAL));
    		negativaPerfilamiento.setSituacionFinancieraActual(porcentajeInversiones);
    		negativaPerfilamiento.setPerfil(rs.getString(NegativaPerfilamientoConstantesHelper.PERFIL));
    		negativaPerfilamiento.setInconsistencias(rs.getString(NegativaPerfilamientoConstantesHelper.INCONSISTENCIAS));
    		negativaPerfilamiento.setEstadoLogico(rs.getBoolean("ESTADO_LOGICO"));
		
		return negativaPerfilamiento;
	}

}	

