package com.aforebanamex.plata.cg.dominio.helper;

public class DOMINIOConstantesHelper {

	private DOMINIOConstantesHelper() {
	}

	public static final String ID_MODULO = "idModulo";
	public static final String CVE_PROCESO_ID = "cveProcesoId";
	public static final String CLAVE = "clave";
	public static final String DESCRIPCION = "descripcion";
	public static final String ESTADO_LOGICO = "estadoLogico";
	public static final String CVE_SUBPROCESO_ID = "cveSubProcesoId";
	public static final String RUTA = "ruta";

	public static final String AND = " AND ";
	public static final String WHERE = " WHERE 1=1 ";
	public static final String LIMIT = " LIMIT ";
	public static final String COMA = ",";
	public static final String WHERE_ROWN = " WHERE ROWN ";
	public static final String BETWEEN = " BETWEEN ";

	public static final String CONTRATO_NOCONTRATO = " AND NOCONTRATO LIKE '%";
	public static final String CONTRATO_NOCONTRATO_CIERRE = "%'";
	
	public static final String CONTRATO_DIGITO = " AND DIGITO LIKE '%";
	public static final String CONTRATO_DIGITO_CIERRE = "%'";
	
	public static final String CONTRATO_DV = " AND DV LIKE '%";
	public static final String CONTRATO_DV_CIERRE = "%'";
	
	public static final String CONTRATO_ESTATUS = " AND ESTATUS LIKE '%";
	public static final String CONTRATO_ESTATUS_CIERRE = "%'";
	
	public static final String CONTRATO_PERFIL = " AND PERFIL LIKE '%";
	public static final String CONTRATO_PERFIL_CIERRE = "%'";
	
	public static final String CONTRATO_PORTAFOLIO = " AND PORTAFOLIO LIKE '%";
	public static final String CONTRATO_PORTAFOLIO_CIERRE = "%'";
	
	public static final String CONTRATO_CLABE = " AND CLABE LIKE '%";
	public static final String CONTRATO_CLABE_CIERRE = "%'";
	
	public static final String CONTRATO_STIPOPORT = " AND STIPOPORT LIKE '%";
	public static final String CONTRATO_STIPOPORT_CIERRE = "%'";
	
	public static final String CONTRATO_LIBRO = " AND LIBRO LIKE '%";
	public static final String CONTRATO_LIBRO_CIERRE = "%'";
	
	
	
	public static final String CONTRATO_ASESORINVERSION = " AND ASESORINVERSION LIKE '%";
	public static final String CONTRATO_ASESORINVERSION_CIERRE = "%'";
	
	public static final String CONTRATO_TIPOMANIFIESTO = " AND TIPOMANIFIESTO LIKE '%";
	public static final String CONTRATO_TIPOMANIFIESTO_CIERRE = "%'";
	
	public static final String CONTRATO_SERVICIOINVERSION = " AND SERVICIOINVERSION LIKE '%";
	public static final String CONTRATO_SERVICIOINVERSION_CIERRE = "%'";
	
	public static final String CONTRATO_CARTAEJECUCION1 = " AND CARTAEJECUCION1 LIKE '%";
	public static final String CONTRATO_CARTAEJECUCION1_CIERRE = "%'";
	
	public static final String CONTRATO_FECHACARTAEJECUCION1 = " AND FECHACARTAEJECUCION1 LIKE '%";
	public static final String CONTRATO_FECHACARTAEJECUCION1_CIERRE = "%'";
	
	public static final String CONTRATO_CARTAEJECUCION2 = " AND CARTAEJECUCION2 LIKE '%";
	public static final String CONTRATO_CARTAEJECUCION2_CIERRE = "%'";
	
	public static final String CONTRATO_FECHACARTAEJECUCION2 = " AND FECHACARTAEJECUCION2 LIKE '%";
	public static final String CONTRATO_FECHACARTAEJECUCION2_CIERRE = "%'";
	
	
	public static final String CONTRATO_JUSTIFICACIONINSTITUCIONAL = " AND JUSTIFICACIONINSTITUCIONAL LIKE '%";
	public static final String CONTRATO_JUSTIFICACIONINSTITUCIONAL_CIERRE = "%'";
	
	public static final String CONTRATO_FECHAINSTITUCIONAL = " AND FECHAINSTITUCIONAL LIKE '%";
	public static final String CONTRATO_FECHAINSTITUCIONAL_CIERRE = "%'";
	
	public static final String CONTRATO_SOFISTICADO = " AND SOFISTICADO LIKE '%";
	public static final String CONTRATO_SOFISTICADO_CIERRE = "%'";
	
	public static final String CONTRATO_JUSTIFICACIONSOFISTICADO = " AND JUSTIFICACIONSOFISTICADO LIKE '%";
	public static final String CONTRATO_JUSTIFICACIONSOFISTICADO_CIERRE = "%'";
	
	public static final String CONTRATO_FECHASOFISTICADO = " AND FECHASOFISTICADO LIKE '%";
	public static final String CONTRATO_FECHASOFISTICADO_CIERRE = "%'";
	
	public static final String CONTRATO_ELEGIBLE = " AND ELEGIBLE LIKE '%";
	public static final String CONTRATO_ELEGIBLE_CIERRE = "%'";
	
	public static final String CONTRATO_JUSTIFICACIONELEGIBLE = " AND JUSTIFICACIONELEGIBLE LIKE '%";
	public static final String CONTRATO_JUSTIFICACIONELEGIBLE_CIERRE = "%'";
	
	public static final String CONTRATO_FECHAELEGIBLE = " AND FECHAELEGIBLE LIKE '%";
	public static final String CONTRATO_FECHAELEGIBLE_CIERRE = "%'";
	
	public static final String CONTRATO_CALIFICADO = " AND CALIFICADO LIKE '%";
	public static final String CONTRATO_CALIFICADO_CIERRE = "%'";
	
	public static final String CONTRATO_JUSTIFICACIONCALIFICADO = " AND JUSTIFICACIONCALIFICADO LIKE '%";
	public static final String CONTRATO_JUSTIFICACIONCALIFICADO_CIERRE = "%'";
	
	public static final String CONTRATO_FECHACALIFICADO = " AND FECHACALIFICADO LIKE '%";
	public static final String CONTRATO_FECHACALIFICADO_CIERRE = "%'";
	
	public static final String CONTRATO_DISCRECIONAL = " AND DISCRECIONAL LIKE '%";
	public static final String CONTRATO_DISCRECIONAL_CIERRE = "%'";
	
	public static final String CONTRATO_JUSTIFICACIONDISCRECIONAL = " AND JUSTIFICACIONDISCRECIONAL LIKE '%";
	public static final String CONTRATO_JUSTIFICACIONDISCRECIONAL_CIERRE = "%'";
	
	public static final String CONTRATO_FECHADISCRECIONAL = " AND FECHADISCRECIONAL LIKE '%";
	public static final String CONTRATO_FECHADISCRECIONAL_CIERRE = "%'";
	
	public static final String CONTRATO_INSTRDEUDAGUB = " AND INSTRDEUDAGUB LIKE '%";
	public static final String CONTRATO_INSTRDEUDAGUB_CIERRE = "%'";
	
	public static final String CONTRATO_INSTRDEUDACORP = " AND INSTRDEUDACORP LIKE '%";
	public static final String CONTRATO_INSTRDEUDACORP_CIERRE = "%'";
	
	public static final String CONTRATO_SOCIEDADESINVER = " AND SOCIEDADESINVER LIKE '%";
	public static final String CONTRATO_SOCIEDADESINVER_CIERRE = "%'";
	
	public static final String CONTRATO_VALORESESTRUC = " AND VALORESESTRUC LIKE '%";
	public static final String CONTRATO_VALORESESTRUC_CIERRE = "%'";
	
	public static final String CONTRATO_CERTBURFIDEICOMISOS = " AND CERTBURFIDEICOMISOS LIKE '%";
	public static final String CONTRATO_CERTBURFIDEICOMISOS_CIERRE = "%'";
	
	public static final String CONTRATO_TITULOSOPCIONALES = " AND TITULOSOPCIONALES LIKE '%";
	public static final String CONTRATO_TITULOSOPCIONALES_CIERRE = "%'";
	
	public static final String CONTRATO_ACCIONES = " AND ACCIONES LIKE '%";
	public static final String CONTRATO_ACCIONES_CIERRE = "%'";
	
	public static final String CONTRATO_VALORESEXTR = " AND VALORESEXTR LIKE '%";
	public static final String CONTRATO_VALORESEXTR_CIERRE = "%'";
	
	
	
	
	
	public static final String TITULARCONTRATO_NOMBRE = " AND NOMBRE LIKE '%";
	public static final String TITULARCONTRATO_NOMBRE_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_ACTIVIDAD = " AND ACTIVIDAD LIKE '%";
	public static final String TITULARCONTRATO_ACTIVIDAD_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_NOCLIENTEBANAMEX = " AND NOCLIENTEBANAMEX LIKE '%";
	public static final String TITULARCONTRATO_NOCLIENTEBANAMEX_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_INST = " AND INST LIKE '%";
	public static final String TITULARCONTRATO_INST_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_NOCTA = " AND NOCTA LIKE '%";
	public static final String TITULARCONTRATO_NOCTA_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_SUC = " AND SUC LIKE '%";
	public static final String TITULARCONTRATO_SUC_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CLABE = " AND CLABE LIKE '%";
	public static final String TITULARCONTRATO_CLABE_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CALLE = " AND CALLE LIKE '%";
	public static final String TITULARCONTRATO_CALLE_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_NOEXT = " AND NOEXT LIKE '%";
	public static final String TITULARCONTRATO_NOEXT_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_NOINTERIOR = " AND NOINTERIOR LIKE '%";
	public static final String TITULARCONTRATO_NOINTERIOR_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_MEXEXTR = " AND MEXEXTR LIKE '%";
	public static final String TITULARCONTRATO_MEXEXTR_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CP = " AND CP LIKE '%";
	public static final String TITULARCONTRATO_CP_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_ESTADO = " AND ESTADO LIKE '%";
	public static final String TITULARCONTRATO_ESTADO_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_DELMPO = " AND DELMPO LIKE '%";
	public static final String TITULARCONTRATO_DELMPO_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CIUDAD = " AND CIUDAD LIKE '%";
	public static final String TITULARCONTRATO_CIUDAD_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_COLONIA = " AND COLONIA LIKE '%";
	public static final String TITULARCONTRATO_COLONIA_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CORRESPONDENCIA = " AND CORRESPONDENCIA LIKE '%";
	public static final String TITULARCONTRATO_CORRESPONDENCIA_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_RFC = " AND RFC LIKE '%";
	public static final String TITULARCONTRATO_RFC_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CURP = " AND CURP LIKE '%";
	public static final String TITULARCONTRATO_CURP_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_FECNAC = " AND FECNAC LIKE '%";
	public static final String TITULARCONTRATO_FECNAC_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_ESCOLARIDAD = " AND ESCOLARIDAD LIKE '%";
	public static final String TITULARCONTRATO_ESCOLARIDAD_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_EDOCIVIL = " AND EDOCIVIL LIKE '%";
	public static final String TITULARCONTRATO_EDOCIVIL_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_SEXO = " AND SEXO LIKE '%";
	public static final String TITULARCONTRATO_SEXO_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_TIPOVIVIENDA = " AND TIPOVIVIENDA LIKE '%";
	public static final String TITULARCONTRATO_TIPOVIVIENDA_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_CALIDADMIGRATORIA = " AND CALIDADMIGRATORIA LIKE '%";
	public static final String TITULARCONTRATO_CALIDADMIGRATORIA_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_PAISRESIDENCIA = " AND PAISRESIDENCIA LIKE '%";
	public static final String TITULARCONTRATO_PAISRESIDENCIA_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_NACIONALIDAD = " AND NACIONALIDAD LIKE '%";
	public static final String TITULARCONTRATO_NACIONALIDAD_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_PAISNAC = " AND PAISNAC LIKE '%";
	public static final String TITULARCONTRATO_PAISNAC_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_EDONAC = " AND EDONAC LIKE '%";
	public static final String TITULARCONTRATO_EDONAC_CIERRE = "%'";
	
	public static final String TITULARCONTRATO_EMPLEADOGROFINBANAMEX = " AND EMPLEADOGROFINBANAMEX LIKE '%";
	public static final String TITULARCONTRATO_EMPLEADOGROFINBANAMEX_CIERRE = "%'";
	
	public static final String BENEFICIARIO_NOMBRE = " AND NOMBRE LIKE '%";
	public static final String BENEFICIARIO_NOMBRE_CIERRE = "%'";
	
	public static final String BENEFICIARIO_APPATERNO = " AND APPATERNO LIKE '%";
	public static final String BENEFICIARIO_APPATERNO_CIERRE = "%'";
	
	public static final String BENEFICIARIO_APMATERNO = " AND APMATERNO LIKE '%";
	public static final String BENEFICIARIO_APMATERNO_CIERRE = "%'";
	
	public static final String BENEFICIARIO_PORCENTAJE = " AND PORCENTAJE LIKE '%";
	public static final String BENEFICIARIO_PORCENTAJE_CIERRE = "%'";
	
	public static final String LIMITANTE_GRUPOINSTRUMENTO = " AND GRUPOINSTRUMENTO LIKE '%";
	public static final String LIMITANTE_GRUPOINSTRUMENTO_CIERRE = "%'";
	
	public static final String LIMITANTE_TIPOVALOR = " AND TIPOVALOR LIKE '%";
	public static final String LIMITANTE_TIPOVALOR_CIERRE = "%'";
	
	public static final String LIMITANTE_EMISORAS = " AND EMISORAS LIKE '%";
	public static final String LIMITANTE_EMISORAS_CIERRE = "%'";
	
	public static final String LIMITANTE_TIPOVALOREMISORA = " AND TIPOVALOREMISORA LIKE '%";
	public static final String LIMITANTE_TIPOVALOREMISORA_CIERRE = "%'";
	
	public static final String EMISOR_EMISOR = " AND EMISOR LIKE '%";
	public static final String EMISOR_EMISOR_CIERRE = "%'";
	
	public static final String EMISOR_RELACION = " AND RELACION LIKE '%";
	public static final String EMISOR_RELACION_CIERRE = "%'";
	
	
	public static final String FIRMAAUTORIZADA_NOMBRE = " AND NOMBRE LIKE '%";
	public static final String FIRMAAUTORIZADA_NOMBRE_CIERRE = "%'";
	
	public static final String FIRMAAUTORIZADA_APPATERNO = " AND APPATERNO LIKE '%";
	public static final String FIRMAAUTORIZADA_APPATERNO_CIERRE = "%'";
	
	public static final String FIRMAAUTORIZADA_APMATERNO = " AND APMATERNO LIKE '%";
	public static final String FIRMAAUTORIZADA_APMATERNO_CIERRE = "%'";
	
	public static final String FIRMAAUTORIZADA_NOESCR = " AND NOESCR LIKE '%";
	public static final String FIRMAAUTORIZADA_NOESCR_CIERRE = "%'";
	
	public static final String FIRMAAUTORIZADA_NONOT = " AND NONOT LIKE '%";
	public static final String FIRMAAUTORIZADA_NONOT_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SUCURSAL = " AND SUCURSAL LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SUCURSAL_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_OPERACION = " AND OPERACION LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_OPERACION_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_TIPO = " AND TIPO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_TIPO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_MEDLIQ = " AND MEDLIQ LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_MEDLIQ_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_CONTRATO = " AND CONTRATO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_CONTRATO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SUBTIPOPORTAFOLIO = " AND SUBTIPOPORTAFOLIO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SUBTIPOPORTAFOLIO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_DIGITO = " AND DIGITO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_DIGITO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_TITULAR = " AND TITULAR LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_TITULAR_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SALDO = " AND SALDO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SALDO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_CONTRATOEGRESO = " AND CONTRATOEGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_CONTRATOEGRESO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_DIGITOEGRESO = " AND DIGITOEGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_DIGITOEGRESO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SALDOINICIALEGRESO = " AND SALDOINICIALEGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SALDOINICIALEGRESO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SALDOCALCULADOEGRESO = " AND SALDOCALCULADOEGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SALDOCALCULADOEGRESO_CIERRE = "%'";
	
	
	public static final String INSTRUCCIONEFECTIVO_CONTRATOINGRESO = " AND CONTRATOINGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_CONTRATOINGRESO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_DIGITOINGRESO = " AND DIGITOINGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_DIGITOINGRESO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SALDOINICIALINGRESO = " AND SALDOINICIALINGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SALDOINICIALINGRESO_CIERRE = "%'";
	
	public static final String INSTRUCCIONEFECTIVO_SALDOCALCULADOINGRESO = " AND SALDOCALCULADOINGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_SALDOCALCULADOINGRESO_CIERRE = "%'";
	
	
	public static final String INSTRUCCIONEFECTIVO_IMPORTEINGRESO = " AND IMPORTEINGRESO LIKE '%";
	public static final String INSTRUCCIONEFECTIVO_IMPORTEINGRESO_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_OPCDISTRINSTRUCCIONES = " AND OPCDISTRINSTRUCCIONES LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_OPCDISTRINSTRUCCIONES_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_CAPTURADOS = " AND CAPTURADOS LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_CAPTURADOS_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_CONTRATO = " AND CONTRATO LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_CONTRATO_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_FOLIOMOV = " AND FOLIOMOV LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_FOLIOMOV_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_DIGITO = " AND DIGITO LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_DIGITO_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_IMPORTENETO = " AND IMPORTENETO LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_IMPORTENETO_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_DEPOSITOS = " AND DEPOSITOS LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_DEPOSITOS_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_RETIROS = " AND RETIROS LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_RETIROS_CIERRE = "%'";
	
	public static final String DISTRIBUCIONINSTRUCCIONES_SUCURSAL = " AND SUCURSAL LIKE '%";
	public static final String DISTRIBUCIONINSTRUCCIONES_SUCURSAL_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_CONTRATO = " AND CONTRATO LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_CONTRATO_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_NOMBRE = " AND NOMBRE LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_NOMBRE_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PERFILACTUAL = " AND PERFILACTUAL LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PERFILACTUAL_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PERSONAPERFILAR = " AND PERSONAPERFILAR LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PERSONAPERFILAR_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJELIQUIDEZ = " AND PORCENTAJELIQUIDEZ LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJELIQUIDEZ_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOLIQUIDEZ = " AND MONTOLIQUIDEZ LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOLIQUIDEZ_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJECORTOPLAZO = " AND PORCENTAJECORTOPLAZO LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJECORTOPLAZO_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOCORTOPLAZO = " AND MONTOCORTOPLAZO LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOCORTOPLAZO_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJELARGOPLAZO = " AND PORCENTAJELARGOPLAZO LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJELARGOPLAZO_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOLARGOPLAZO = " AND MONTOLARGOPLAZO LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOLARGOPLAZO_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJEPATRIMONIOLIQUIDOTOTAL = " AND PORCENTAJEPATRIMONIOLIQUIDOTOTAL LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJEPATRIMONIOLIQUIDOTOTAL_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOPATRIMONIOLIQUIDOTOTAL = " AND MONTOPATRIMONIOLIQUIDOTOTAL LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_MONTOPATRIMONIOLIQUIDOTOTAL_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_INTERVALOEDAD = " AND INTERVALOEDAD LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_INTERVALOEDAD_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_NIVELESTUDIOS = " AND NIVELESTUDIOS LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_NIVELESTUDIOS_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_OCUPACION = " AND OCUPACION LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_OCUPACION_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_ACTIVIDADPROFESIONALANTERIOR = " AND ACTIVIDADPROFESIONALANTERIOR LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_ACTIVIDADPROFESIONALANTERIOR_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_ACTIVIDADPROFESIONALACTUAL = " AND ACTIVIDADPROFESIONALACTUAL LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_ACTIVIDADPROFESIONALACTUAL_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_ACTIVIDADRELACIONADAINVERSIONES = " AND ACTIVIDADRELACIONADAINVERSIONES LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_ACTIVIDADRELACIONADAINVERSIONES_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_ESTRATEGIACLIENTE = " AND ESTRATEGIACLIENTE LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_ESTRATEGIACLIENTE_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_CLIENTEASESORIA = " AND CLIENTEASESORIA LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_CLIENTEASESORIA_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPERIENCIADEUDAGUB = " AND EXPERIENCIADEUDAGUB LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPERIENCIADEUDAGUB_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIADEUDAGUB = " AND FRECUENCIADEUDAGUB LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIADEUDAGUB_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZODEUDAGUB = " AND PLAZODEUDAGUB LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZODEUDAGUB_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENDEUDAGUB = " AND VOLUMENDEUDAGUB LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENDEUDAGUB_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPDEUDACORP = " AND EXPDEUDACORP LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPDEUDACORP_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIADEUDACORP = " AND FRECUENCIADEUDACORP LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIADEUDACORP_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZODEUDACORP = " AND PLAZODEUDACORP LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZODEUDACORP_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENDEUDACORP = " AND VOLUMENDEUDACORP LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENDEUDACORP_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPSOCIEDADESINV = " AND EXPSOCIEDADESINV LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPSOCIEDADESINV_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIASOCIEDADESINV = " AND FRECUENCIASOCIEDADESINV LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIASOCIEDADESINV_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZOSOCIEDADESINV = " AND PLAZOSOCIEDADESINV LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZOSOCIEDADESINV_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENSOCIEDADESINV = " AND VOLUMENSOCIEDADESINV LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENSOCIEDADESINV_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPVALORESEST = " AND EXPVALORESEST LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPVALORESEST_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIAVALORESEST = " AND FRECUENCIAVALORESEST LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIAVALORESEST_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZOVALORESEST = " AND PLAZOVALORESEST LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZOVALORESEST_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENVALORESEST = " AND VOLUMENVALORESEST LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENVALORESEST_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPCERTIFICADOSBUR = " AND EXPCERTIFICADOSBUR LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_EXPCERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIACERTIFICADOSBUR = " AND FRECUENCIACERTIFICADOSBUR LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_FRECUENCIACERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZOCERTIFICADOSBUR = " AND PLAZOCERTIFICADOSBUR LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PLAZOCERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENCERTIFICADOSBUR = " AND VOLUMENCERTIFICADOSBUR LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_VOLUMENCERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_TIENELIMITANTE = " AND TIENELIMITANTE LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_TIENELIMITANTE_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJETOTALPATRIMONIO = " AND PORCENTAJETOTALPATRIMONIO LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJETOTALPATRIMONIO_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJEINGRESOANUAL = " AND PORCENTAJEINGRESOANUAL LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJEINGRESOANUAL_CIERRE = "%'";
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJEINVERSIONES = " AND PORCENTAJEINVERSIONES LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PORCENTAJEINVERSIONES_CIERRE = "%'";
	
	
	public static final String REPERFILAMIENTOPERSONAFISICA_PERFIL = " AND PERFIL LIKE '%";
	public static final String REPERFILAMIENTOPERSONAFISICA_PERFIL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_CONTRATO = " AND CONTRATO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_CONTRATO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_NOMBRE = " AND NOMBRE LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_NOMBRE_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PERFILACTUAL = " AND PERFILACTUAL LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PERFILACTUAL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PERSONAPERFILAR = " AND PERSONAPERFILAR LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PERSONAPERFILAR_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJELIQUIDEZ = " AND PORCENTAJELIQUIDEZ LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJELIQUIDEZ_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_MONTOLIQUIDEZ = " AND MONTOLIQUIDEZ LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_MONTOLIQUIDEZ_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJECORTOPLAZO = " AND PORCENTAJECORTOPLAZO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJECORTOPLAZO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_MONTOCORTOPLAZO = " AND MONTOCORTOPLAZO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_MONTOCORTOPLAZO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJELARGOPLAZO = " AND PORCENTAJELARGOPLAZO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJELARGOPLAZO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_MONTOLARGOPLAZO = " AND MONTOLARGOPLAZO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_MONTOLARGOPLAZO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJEPATRIMONIOLIQUIDOTOTAL = " AND PORCENTAJEPATRIMONIOLIQUIDOTOTAL LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJEPATRIMONIOLIQUIDOTOTAL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_MONTOPATRIMONIOLIQUIDOTOTAL = " AND MONTOPATRIMONIOLIQUIDOTOTAL LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_MONTOPATRIMONIOLIQUIDOTOTAL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_INTERVALOEDAD = " AND INTERVALOEDAD LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_INTERVALOEDAD_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_NIVELESTUDIOS = " AND NIVELESTUDIOS LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_NIVELESTUDIOS_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_OCUPACION = " AND OCUPACION LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_OCUPACION_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_ACTIVIDADPROFESIONALANTERIOR = " AND ACTIVIDADPROFESIONALANTERIOR LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_ACTIVIDADPROFESIONALANTERIOR_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_ACTIVIDADPROFESIONALACTUAL = " AND ACTIVIDADPROFESIONALACTUAL LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_ACTIVIDADPROFESIONALACTUAL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_ACTIVIDADRELACIONADAINVERSIONES = " AND ACTIVIDADRELACIONADAINVERSIONES LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_ACTIVIDADRELACIONADAINVERSIONES_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_ESTRATEGIACLIENTE = " AND ESTRATEGIACLIENTE LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_ESTRATEGIACLIENTE_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_CLIENTEASESORIA = " AND CLIENTEASESORIA LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_CLIENTEASESORIA_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPERIENCIADEUDAGUB = " AND EXPERIENCIADEUDAGUB LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPERIENCIADEUDAGUB_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIADEUDAGUB = " AND FRECUENCIADEUDAGUB LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIADEUDAGUB_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZODEUDAGUB = " AND PLAZODEUDAGUB LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZODEUDAGUB_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENDEUDAGUB = " AND VOLUMENDEUDAGUB LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENDEUDAGUB_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPDEUDACORP = " AND EXPDEUDACORP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPDEUDACORP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIADEUDACORP = " AND FRECUENCIADEUDACORP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIADEUDACORP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZODEUDACORP = " AND PLAZODEUDACORP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZODEUDACORP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENDEUDACORP = " AND VOLUMENDEUDACORP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENDEUDACORP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPSOCIEDADESINV = " AND EXPSOCIEDADESINV LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPSOCIEDADESINV_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIASOCIEDADESINV = " AND FRECUENCIASOCIEDADESINV LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIASOCIEDADESINV_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOSOCIEDADESINV = " AND PLAZOSOCIEDADESINV LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOSOCIEDADESINV_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENSOCIEDADESINV = " AND VOLUMENSOCIEDADESINV LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENSOCIEDADESINV_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPVALORESEST = " AND EXPVALORESEST LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPVALORESEST_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIAVALORESEST = " AND FRECUENCIAVALORESEST LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIAVALORESEST_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOVALORESEST = " AND PLAZOVALORESEST LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOVALORESEST_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENVALORESEST = " AND VOLUMENVALORESEST LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENVALORESEST_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPCERTIFICADOSBUR = " AND EXPCERTIFICADOSBUR LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPCERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIACERTIFICADOSBUR = " AND FRECUENCIACERTIFICADOSBUR LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIACERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOCERTIFICADOSBUR = " AND PLAZOCERTIFICADOSBUR LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOCERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENCERTIFICADOSBUR = " AND VOLUMENCERTIFICADOSBUR LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENCERTIFICADOSBUR_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPTITULOSOPC = " AND EXPTITULOSOPC LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPTITULOSOPC_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIATITULOSOPC = " AND FRECUENCIATITULOSOPC LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIATITULOSOPC_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOTITULOSOPC = " AND PLAZOTITULOSOPC LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOTITULOSOPC_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENTITULOSOPC = " AND VOLUMENTITULOSOPC LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENTITULOSOPC_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPACCIONES = " AND EXPACCIONES LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPACCIONES_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIAACCIONES = " AND FRECUENCIAACCIONES LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIAACCIONES_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOACCIONES = " AND PLAZOACCIONES LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOACCIONES_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENACCIONES = " AND VOLUMENACCIONES LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENACCIONES_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPVALORESEXT = " AND EXPVALORESEXT LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPVALORESEXT_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIAVALORESEXT = " AND FRECUENCIAVALORESEXT LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIAVALORESEXT_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOVALORESEXT = " AND PLAZOVALORESEXT LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOVALORESEXT_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENVALORESEXT = " AND VOLUMENVALORESEXT LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENVALORESEXT_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPTRACKERS = " AND EXPTRACKERS LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPTRACKERS_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIATRACKERS = " AND FRECUENCIATRACKERS LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIATRACKERS_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOTRACKERS = " AND PLAZOTRACKERS LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOTRACKERS_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENTRACKERS = " AND VOLUMENTRACKERS LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENTRACKERS_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_EXPCERTIFICADOSCAP = " AND EXPCERTIFICADOSCAP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_EXPCERTIFICADOSCAP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIACERTIFICADOSCAP = " AND FRECUENCIACERTIFICADOSCAP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_FRECUENCIACERTIFICADOSCAP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PLAZOCERTIFICADOSCAP = " AND PLAZOCERTIFICADOSCAP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PLAZOCERTIFICADOSCAP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENCERTIFICADOSCAP = " AND VOLUMENCERTIFICADOSCAP LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_VOLUMENCERTIFICADOSCAP_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PROPOSITOINVERSION = " AND PROPOSITOINVERSION LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PROPOSITOINVERSION_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_TOLERANCIARIESGO = " AND TOLERANCIARIESGO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_TOLERANCIARIESGO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_HORIZONTEINVERSION = " AND HORIZONTEINVERSION LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_HORIZONTEINVERSION_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_TIENELIMITANTE = " AND TIENELIMITANTE LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_TIENELIMITANTE_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJETOTALPATRIMONIO = " AND PORCENTAJETOTALPATRIMONIO LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJETOTALPATRIMONIO_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJEINGRESOANUAL = " AND PORCENTAJEINGRESOANUAL LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJEINGRESOANUAL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJEINVERSIONES = " AND PORCENTAJEINVERSIONES LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PORCENTAJEINVERSIONES_CIERRE = "%'";
	
	
	public static final String NEGATIVAPERFILAMIENTO_PERFIL = " AND PERFIL LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_PERFIL_CIERRE = "%'";
	
	public static final String NEGATIVAPERFILAMIENTO_INCONSISTENCIAS = " AND INCONSISTENCIAS LIKE '%";
	public static final String NEGATIVAPERFILAMIENTO_INCONSISTENCIAS_CIERRE = "%'";
	

	
	public static final int CODIGO_ERROR = 415;
	public static final int CODIGO_EXITO = 200;
	public static final String ERROR_REGISTRO_DUPLICADO = " Ya existe un registro con las mismas características.";
	public static final String ERROR_ACTUALIZACION_BD = " No se pudo realizar la actualización.";
	public static final String EXITO_REGISTRO = " Se realizo el registro de forma correcta.";
	public static final String EXITO_ACTUALIZA_REGISTRO = " Se actalizo el registro de forma correcta.";
	public static final String EXITO_ELIMINADO_REGISTRO = " Se elimino el registro de forma correcta.";
	public static final String ERROR_ELIMINADO_REGISTRO ="Registro con las mismas características se encuentra con estado eliminado.";
	public static final String ERROR_ELIMINADO = " No se pudo elimar el registro.";
	public static final String ERROR_CARACTERES_NO_VALIDOS ="No se permiten los caracteres [']";
}
